state: KY

links:
- name: primary
  url: https://chfs.ky.gov/agencies/dph/PublishingImages/CV19VacStatus.JPG

- name: secondary
  url: https://chfs.ky.gov/agencies/dph/PublishingImages/Cv19CasesandVaccinations.JPG

- name: age-and-vaccination
  url: https://chfs.ky.gov/agencies/dph/PublishingImages/cv19vacstatusandage.jpg
  
- name: mortality-rate
  url: https://chfs.ky.gov/agencies/dph/PublishingImages/Cv19CasesandVaccinations.JPG

