state: GL

links:
- name: variables
  url: https://docs.google.com/spreadsheets/d/1aR4L0VStsBrY37aRKTjlUwjQuPS3hDwdRyTwGInkRyE/export?format=csv&gid=1217608216
  file: csv

- name: supply_tracker
  url: https://docs.google.com/spreadsheets/d/1aR4L0VStsBrY37aRKTjlUwjQuPS3hDwdRyTwGInkRyE/export?format=csv&gid=44085690
  file: csv

- name: bilateral_deal
  url: https://docs.google.com/spreadsheets/d/1aR4L0VStsBrY37aRKTjlUwjQuPS3hDwdRyTwGInkRyE/export?format=csv&gid=696122761
  file: csv

- name:  donation_delivered
  url: https://docs.google.com/spreadsheets/d/1aR4L0VStsBrY37aRKTjlUwjQuPS3hDwdRyTwGInkRyE/export?format=csv&gid=299065699
  file: csv
  
- name:  who_vaccination_data
  url: https://covid19.who.int/who-data/vaccination-data.csv
  file: csv  
  
